### ISSUE TITLE
As a developer I need to do small fixes to the Inspector tool

### ISSUE THREAD

**Issue by lilimelgar** [beeldengeluid/labo-components#263] opened 2019-01-22 12:26 UTC
Where: in the Inspector tool
See this [screencast](https://drive.google.com/drive/u/1/folders/0B8StOK8IHMiQX0F1akJhLUV2akE) for illustration.

Things to fix:
- [x] Adjust type of chart. The best chart for this tool is a stacked bar chart with a single vertical bar per year showing which part is missing and which part is complete (this was solved in issue #221. The missing + complete should equal the total records for that year. At this moment, the bars are divided in two, showing one next to each other
- [x] In a previous version of the master branch, the fields in the drop down list "Metadata field for date (x-axis) were showing the percentage of completeness. That information was very useful, but it is now gone. See how it was before:
![screen shot 2019-01-22 at 13 31 44](https://user-images.githubusercontent.com/8133228/51535909-23e2f380-1e4a-11e9-8f2c-1c5f0fb8250e.png)
- [x] The number formatting implemented in issue #229 should also be applied to this window (see numbers on the bottom right):
![screen shot 2019-01-22 at 13 58 06](https://user-images.githubusercontent.com/8133228/51537068-c81a6980-1e4d-11e9-9660-6c1ec40efa83.png)

**Comment by avlisodraude** [comment] 2019-01-23 08:13
@lilimelgar  @jblom 
Issue done in labo-components branch _"task/#263-inspector-tool-adjustments"_

@lilimelgar : Please test in already mentioned branch and close/comment accordingly.

**What was done?** (per requested point, screenshots after explanation )
- Adjust type of chart as a stacked bar. **_Done_**
- Metadata field for date (x-axis) were showing the percentage of completeness.  **_This issue is already solved in Master branch so nothing needed to be changed there._** 
- The number formatting for the 'Completeness' in the 'current selected field'. **_Formatted using ComponentUtil.formatNumber which picks the toLocaleString up as a number formatter._**

![Screenshot 2019-01-23 at 08.56.51.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/0a1b4d8d-83e0-483d-b604-0f4efc1b5110)

![Screenshot 2019-01-23 at 08.57.09.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/8fcdf473-3c49-40ac-af73-1eff5604181e)

![Screenshot 2019-01-23 at 08.57.01.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/9bcb4b9a-0d99-4496-babb-3bd3c161421b)

**Comment by lilimelgar** [comment] 2019-01-24 17:47
Tested in branch task/#263-inspector-tool-adjustments. All super!, only two last things to check before sending the pull request:

- [ ] Check why some date fields don't show the completeness percentage?
![screen shot 2019-01-24 at 18 45 59](https://user-images.githubusercontent.com/8133228/51697567-64886b80-2008-11e9-97c8-23d1516517ee.png)

- [ ] It would be very useful to add percentages to the pop-ups in the chart, here:
![screen shot 2019-01-24 at 18 47 18](https://user-images.githubusercontent.com/8133228/51697603-8124a380-2008-11e9-905c-5984d5242ef8.png)

**Comment by jblom** [comment] 2019-01-28 06:13
@lilimelgar those three points are nice and relatively easy fixes. @avlisodraude I'd say fix these too.

**Comment by avlisodraude** [comment] 2019-02-04 15:25
@lilimelgar @jblom 
__Regarding @lilimelgar last 3 comments:__
__testing branch:__ labo-components branch: __task/#263-inspector-tool-adjustments__

- Check why some date fields don't show the completeness percentage?
-- I haven't been able to reproduce the issue so nothing has been done regarding this point.
- It would be very useful to add percentages to the pop-ups in the chart and
- Please check if it is possible to grab the labels also using the "level", because now in the chart you see only one part of the label, but the level is missing. 

Last 2 comments have been done in the same branch with the following as a result of the changes done:
![Screenshot 2019-02-04 at 16.18.39.png](https://images.zenhubusercontent.com/5a1e745d8a75884b90892ac4/dc7ff3d9-764f-4a8b-8cd4-a3383be65590)

@lilimelgar : __Issue moved back to q/a waiting for reply__ :-)

**Comment by avlisodraude** [comment] 2019-02-05 09:03
@lilimelgar @jblom 
Already tested along with @lilimelgar  and ready to be closed/merged.

**Comment by jblom** [comment] 2019-02-05 13:19
@avlisodraude @lilimelgar alright I merged both PRs related to this issue (after a bit of code cleaning). I found one bug, which I will report right away. Also I really do not like the way the collection inspector relies on heavy communication with the search API. Will also write a story to extend the search API with a smart function to get the statistics of all fields of a collection in one call.

**Closed by jblom** 2019-02-05 13:19 UTC
Labels: Tested, Theme: collection analysis, enhancement
