### ISSUE TITLE
As a developer, I need to fix a small bug with the highlighted bookmarks in the Search tool when switching between user projects

### ISSUE THREAD

**Issue by lilimelgar** [beeldengeluid/labo-components#408] opened 2019-06-05 15:43 UTC
Where: In the Search tool.
Issue: if you are in User project No.1 and bookmark a number of items, and then switch to User project No.2, which doesn't have those items bookmarked, they still show in the same colour and when they have been bookmarked. See [screencast](https://drive.google.com/open?id=1APHl59asFrybsDBro_mes3sfft5N3s9I). In the screencast you can see that when I changed to the project "Climate change", the bookmarks I stored in the project "Desmet films..." still show in orange. It doesn't happen all the time though...

**Comment by avlisodraude** [comment] 2019-06-16 16:12
@jblom @lilimelgar 

Issue for labo-components project done in branch:
_issue/#408-bookmarkeds-bug-when-switching-user-project_

### Pull request
_https://github.com/beeldengeluid/labo-components/pull/417_

### Description
Bookmarked items don't refresh properly when switching projects 

### How to reproduce
- Keeping a fixed query (constant parameters, ie, collection, search term, facets, date range, field category, etc).
- Selecting and bookmarking a few items (which will be saved in a specific project) these items are shown with a colored background (a CSS 'bookmarked' class is added to those items)
- All bookmarked items are saved per current selected project in localStorage under key value 'activeBookmarks'. This means that if the user changes the current project that list is refreshed and hence the bookmarked items should reflect that in the current result list, which doesn't happened as reported by Liliana.

Another way to test this issue is: 
- While getting some bookmarked item on a selected project 'slow down' API call using the Chrome Developer Tools "Performance => Network => Throttling" feature to simulate slower connections which should be enough to show how the list is not updated when switching the current project.

### Cause:
This happens randomly because it's related to the API call which fetches the active bookmarks to later be saved in localStorage which doesn't wait for the response to reload the items. 

### Solution:
Update the code with a callback to only refresh once the response is back.

**Comment by jwassenaarbg** [comment] 2019-06-17 12:44
Looks good, works as expected. No comments :)

**Comment by jblom** [comment] 2019-06-20 06:53
@avlisodraude @jwassenaarbg checked it as well. Works fine indeed. Closing this

**Closed by jblom** 2019-06-20 06:53 UTC
Labels: bug
