### ISSUE TITLE
As a developer, I need to add a "loading results" message to the graphics

### ISSUE THREAD

**Issue by lilimelgar** [beeldengeluid/labo-components#381] opened 2019-05-02 08:41 UTC
-Where:
Search tool, timeline chart
Inspector tool, timeline chart

-Problem:
Sometimes the graphics take long to load the data, creating confusion when the values don't change immediately. Example: Search tool, KB collection, switching from absolute to relative view for the whole collection takes a long time (the first time), and there is no indication that the application is working on it. See [screencast](https://drive.google.com/drive/u/1/folders/0B8StOK8IHMiQX0F1akJhLUV2akE).

**Comment by jblom** [comment] 2019-05-27 05:21
@lilimelgar @avlisodraude cannot reproduce this one, so closing it for now

**Closed by jblom** 2019-05-27 05:21 UTC
Labels: Theme: UX / usability, Theme: graphics, enhancement
