### ISSUE TITLE
As a user, I need a pointer to the help menu

### ISSUE THREAD

**Issue by lilimelgar** [beeldengeluid/labo-components#206] opened 2018-11-19 12:32 UTC
The approach to solve this is updated (see last comment).

--old--

Where: In the Search tool, search box

**Approach**

Add a tooltip with a link to the documentation
![Screen Shot 2018-11-19 at 13.29.21.png](https://images.zenhubusercontent.com/5a115fba8a75884b9087ff7a/4390ef05-e85d-4fec-96cb-987f4dc572eb)

**Acceptance criteria**
- [ ] Tooltip added next to the search box. When users click on it, it opens the window with the Question mark button  (text: need help?)
- [ ] Tooltip added next to the field cluster selector box. When users click on it, it opens the window with the Question mark button (text: need help?)

**Comment by jblom** [comment] 2018-11-19 15:19
Clear story @lilimelgar , putting in the backlog

**Comment by lilimelgar** [comment] 2018-12-11 15:11
@avlisodraude 
As we discussed, a better solution for this issue is the following:
- [ ] Make the help button more dynamic, so users know where the help texts are. For this, you could use a dynamic pointer to the button, for example, as it is done in this website ([see screencast](https://drive.google.com/drive/folders/0B8StOK8IHMiQX0F1akJhLUV2akE)). The expected behavior is:
--the first time a user enters the page which has a Question mark button on the top right, the dynamic call appears
--the text should say: "Need help?" and point to the button

- [ ] In the Search tool, change the text in the search box here:
![screen shot 2018-12-11 at 15 42 57](https://user-images.githubusercontent.com/8133228/49809421-22a8ac00-fd5f-11e8-9191-15a0c2898159.png)
Instead of "search" write: "Search (How-tos are in the help menu)

**Comment by avlisodraude** [comment] 2019-02-19 15:02
**@lilimelgar ( @jblom  )**
I just pushed a branch in the clariah-mediasuite project named:
issue/#206-help-hint

In this branch I added a hint tooltip to the help button.
By default the btn shows every time the user opens a page (with help content) but it disappear after 6 seconds (this is adjustable). 
Please check if this approach is enough to call attention for the help btn since I've tried other options and it really seems to go a bit over the top in terms of UI.
If you think that we need to add more to either the styling or functionality (do not show anymore button or so) please leave a comment and I'll take care of it.
The issue is still in the In Progress column since I'm doing some cleaning of the code.

**Comment by lilimelgar** [comment] 2019-02-20 14:31
@avlisodraude 
I tested in branch issue/#206-help-hint. This solution works well in my opinion (I will evaluate how it goes with users later on). For the moment, I would suggest:
-Capitalize N (Need help?)
-If not too complicated, it would be good to add the option "don't show this again" that you suggested

**Comment by avlisodraude** [comment] 2019-02-27 12:43
@lilimelgar 
**Regarding both comments:**

- Capitalize N (Need help?) DONE along with some styling to the tooltip itself
- If not too complicated, it would be good to add the option "don't show this again" that you suggested.  _As discussed with @lilimelgar the message to stop showing the tooltip means a lot more changes for will distract the attention from the tooltip to the btn to stop it from running._

The time the tooltip is displayed has been reduce from 4 to 3 seconds (this can be adjusted easily if needed).
All changes have been done in the same branch __"issue/#206-help-hint"__

**Comment by lilimelgar** [comment] 2019-03-04 11:58
@avlisodraude After checking more carefully, these are two last suggestions/questions before making the pull request:
1) Imagine that the user is for long in a page/tool, when s(he) entered, s(he) thought help was not needed, but later on, the user got confused, and perhaps doesn't remember that the help menu was there. Would it be possible to show the "Need help?" button every 5 minutes for instance?
2) If we do this, we would need the option to turn that annoying ;) button off. The solution could be to add a shorter text, such as "Dismiss".
Please check if this is doable withouth too much effort, otherwise, leave it as it is, and do the pull request.

**Comment by jblom** [comment] 2019-03-04 15:32
@lilimelgar @avlisodraude I rejected the code, since it required adding an extra JS library to each page; just for this small feature. 

To solve this issue I've implemented a "vanilla" javascript/CSS solution and pushed it to the master.

I consider this a first pass of the cleaning of the old clariah-mediasuite client side code.

**Comment by jblom** [comment] 2019-03-04 15:33
@lilimelgar so please test one more time and then close this issue please. The additional features can go to a new issue. We'll see if we'll implement that for V4

<img width="171" alt="schermafbeelding 2019-03-04 om 16 12 04" src="https://user-images.githubusercontent.com/917310/53743482-34e84100-3e9b-11e9-959e-5f7a5a84f6a8.png">

**Comment by lilimelgar** [comment] 2019-03-06 12:10
Tested in the Master branch, all Ok.

**Comment by lilimelgar** [comment] 2019-03-06 14:46
@jblom I reopened this one since after testing more, the "need help" message feels a bit intrusive... is it possible to change this for a simpler alternative? for example, that the question mark button changes colour subtly from light to strong? then it becomes more visible without being intrusive. Otherwise, we would need to add a "dismiss" option for not bothering the users too much...

**Comment by jblom** [comment] 2019-03-07 06:19
@lilimelgar sounds good, the message did indeed feel a bit over the top & the design was a bit strange with the need help? pointing to another question mark. @roelandordelman also mentioned this and I think what you suggest now is much more natural. 

I'll remove this functionality from the master for now and then I'll close this issue. After having talked to FW (and asking about this too) we could write another issue or have them fix it very nicely

**Closed by jblom** 2019-03-07 06:19 UTC
Labels: Tested, Theme: UX / usability
